all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: quyet.nguyen
    ansible_become: true
    security_mode: sasl_ssl
preflight:
  hosts:
    kafka-ansible-1:
    10.60.8.201:
    10.60.8.202:
    schema-registry-ansible:
    host-control-ansible:
    connect-ansible:
    ksql-ansible:
ssl_CA:
  hosts:
    kafka-ansible-1:
zookeeper:
  hosts:
    kafka-ansible-1:
    kafka-ansible-2:
    kafka-ansible-3:
broker:
  hosts:
    kafka-ansible-1:
      kafka:
        broker:
          id: 1
    kafka-ansible-2:
      kafka:
        broker:
          id: 2
    kafka-ansible-3:
      kafka:
        broker:
          id: 3
schema-registry:
  hosts:
    schema-registry-ansible:
control-center:
  hosts:
    host-control-ansible:
      confluent:
        control:
          center:
            config:
              confluent.controlcenter.connect.cluster: connect-ansible:8083
connect-distributed:
  hosts:
    connect-ansible:
kafka-rest:
  hosts:
    connect-ansible:
ksql:
  hosts:
    ksql-ansible:
tools:
  hosts:
    kafka-ansible-1: