- name: create ssl certificate directory
  file:
    path: /var/ssl/private
    state: directory
    mode: 0755
    become: true
- name: copy ssl related files to host
  synchronize:
    src: generated_ssl_files/
    dest: /var/ssl/private
    become: true
